### ISSUE TITLE
Marker Icon Customizations

### ISSUE THREAD

**Issue by wpscholar** [wpscholar-wp-plugins/stellar-places#7]
Consider adding the ability to:
- Upload a custom icon to a single location.  Should be able to upload a .PNG (or any image) and everywhere that point shows up, it no longer uses the default red pin.
- Upload a custom icon to a category.  Should be able to upload a .PNG (or any image) and all of the pins for locations in that category will use that image.

Notes: An icon for a single location would always override a category icon. We may want to consider adding the ability to turn off custom icons via map options / shortcode.

**Comment by syntacticNaCl** [comment]
@wpscholar I had to build similar functionality into this plugin for a project I was working on. I currently have it where I can upload a single icon and it will replace all of the map markers with that icon. I understand that you are considering an icon for category and for single location. Would you also like another icon that would be global. So basically a backup icon that replaces all of the map markers if no single or category icons have been uploaded?

**Comment by wpscholar** [comment]
@syntacticNaCl Yes, I'm thinking it would be great to have it at all three levels.

**Comment by wpscholar** [comment]
The latest release (version 1.3) contains the ability to select a custom icon at the global, category, and post level.
